export const notes = [
  {
    id: 1,
    title: 'Note 1',
    content: 'This is the content of Note 1.',
    timestamp: new Date(),
    created: new Date(),
    color: 'blue',
  },
  {
    id: 2,
    title: 'Note 2',
    content: 'This is the content of Note 2.',
    timestamp: new Date(),
    created: new Date(),
    color: 'red',
  },
  {
    id: 3,
    title: 'Note 3',
    content: 'This is the content of Note 3.',
    timestamp: new Date(),
    created: new Date(),
    color: 'green',
  },
  {
    id: 4,
    title: 'Note 4',
    content: 'This is the content of Note 4.',
    timestamp: new Date(),
    created: new Date(),
    color: 'yellow',
  },
  {
    id: 5,
    title: 'Note 5',
    content: 'This is the content of Note 5.',
    timestamp: new Date(),
    created: new Date(),
    color: 'purple',
  },
  {
    id: 6,
    title: 'Note 6',
    content: 'This is the content of Note 6.',
    timestamp: new Date(),
    created: new Date(),
    color: 'orange',
  },
  {
    id: 7,
    title: 'Note 7',
    content: 'This is the content of Note 7.',
    timestamp: new Date(),
    created: new Date(),
    color: 'pink',
  },
  {
    id: 8,
    title: 'Note 8',
    content: 'This is the content of Note 8.',
    timestamp: new Date(),
    created: new Date(),
    color: 'brown',
  },
  {
    id: 9,
    title: 'Note 9',
    content: 'This is the content of Note 9.',
    timestamp: new Date(),
    created: new Date(),
    color: 'gray',
  },
]
